### ISSUE TITLE
socks5 地址是否支持配置域名自动解析成ip

### ISSUE THREAD

**Issue by Ramon403** [L-codes/ltproxy#3]
这个工具完美运行，非常感谢。

就一个小问题，socks5 地址是否支持配置域名自动解析成ip
比如 如下配置
```yml
rules:
  - proxies:
      - socks5 a.xxxx.com 8888 abc 123
```

运行会报错，必须改成ip
proxifier 是可以配域名的
